global
  daemon
  group  haproxy
  log  /dev/log local0
  maxconn  10000
  pidfile  /var/run/haproxy.pid
  user  haproxy

defaults
  log  global
  mode  tcp
  retries  3
  timeout  http-request 10s
  timeout  queue 1m
  timeout  connect 10s
  timeout  client 1m
  timeout  server 1m
  timeout  check 10s

listen admin
    bind *:1936
    acl office_allowed src 218.211.34.185/32 220.130.219.4/32 10.3.0.0/16 127.0.0.0/16 172.0.0.0/8 113.196.126.5/32 210.57.28.18/32
    acl restricted_url path_beg /haproxy
    http-request deny if restricted_url !office_allowed
    option dontlog-normal
    mode http
    stats enable
    stats uri /haproxy?stats
    stats hide-version
    stats refresh 30s
    stats show-node

