[Service]
Type=simple

# High Traffic Optimizations
LimitNOFILE=1000000
LimitNPROC=infinity
LimitMEMLOCK=infinity

ExecStart=
ExecStart=/usr/local/sbin/haproxy -W -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

ExecReload=
ExecReload=/usr/local/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg
ExecReload=/bin/kill -USR2 $MAINPID

ExecStartPre=
ExecStartPre=/usr/local/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg

TimeoutStartSec=15
TimeoutReloadSec=10

KillMode=mixed
Restart=always
